"""
DrugRecall Check API
Pharmacies, healthcare providers, and medtech apps need real-time access to FDA drug recalls, safety alerts, and enforcement reports, but the FDA's open data portal requires developers to navigate complex JSON dumps with no dedicated API key or rate limits suitable for production use. There is no simple, well-documented REST API that returns recall data by drug name, NDC code, manufacturer, or date range with proper pagination and webhook notifications when new recalls hit. Developers building pharmacy management software or patient safety apps hack together scrapers or batch downloads.
Auto-generated by API Factory — 2026-05-05T12:27:35.694450
"""

import os
import uuid
import hashlib
import json
from datetime import datetime
from typing import Optional

from fastapi import FastAPI, Query, Header, HTTPException, Depends, Request
from fastapi.middleware.cors import CORSMiddleware
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from data_pipeline import DataFetcher

# ── Config ──────────────────────────────────────────────────────────
API_KEY = os.environ.get("API_KEY", "dev-key-change-me")
RATE_LIMIT = os.environ.get("RATE_LIMIT_PER_MINUTE", "60/minute")

# ── App Setup ───────────────────────────────────────────────────────
app = FastAPI(
    title="DrugRecall Check API",
    description="""Pharmacies, healthcare providers, and medtech apps need real-time access to FDA drug recalls, safety alerts, and enforcement reports, but the FDA's open data portal requires developers to navigate complex JSON dumps with no dedicated API key or rate limits suitable for production use. There is no simple, well-documented REST API that returns recall data by drug name, NDC code, manufacturer, or date range with proper pagination and webhook notifications when new recalls hit. Developers building pharmacy management software or patient safety apps hack together scrapers or batch downloads.""",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# CORS — allow RapidAPI and any origin in production
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Rate Limiting
limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)


# ── Auth ────────────────────────────────────────────────────────────
def require_auth(x_api_key: str = Header(None)):
    if x_api_key != API_KEY:
        raise HTTPException(status_code=401, detail="Invalid or missing API key")


# ── Real Data Pipeline ─────────────────────────────────────────────
fetcher = DataFetcher()


# ── Routes ──────────────────────────────────────────────────────────

@app.get("/health")
@limiter.limit(RATE_LIMIT)
async def health(request: Request):
    return {"status": "ok", "ts": datetime.utcnow().isoformat(), "version": "1.0.0"}

@app.get("/v1/docs")
@limiter.limit(RATE_LIMIT)
async def api_docs(request: Request, x_api_key: str = Header(None)):
    require_auth(x_api_key)
    return {
        "name": "DrugRecall Check API",
        "description": """Pharmacies, healthcare providers, and medtech apps need real-time access to FDA drug recalls, safety alerts, and enforcement reports, but the FDA's open data portal requires developers to navigate complex JSON dumps with no dedicated API key or rate limits suitable for production use. There is no simple, well-documented REST API that returns recall data by drug name, NDC code, manufacturer, or date range with proper pagination and webhook notifications when new recalls hit. Developers building pharmacy management software or patient safety apps hack together scrapers or batch downloads.""",
        "category": "health",
        "tags": ["health", "fda", "drug-recall", "pharmacy", "compliance", "safety", "healthcare"],
        "version": "1.0.0",
        "endpoints": [
        {
                "path": "/v1/recalls/search",
                "method": "GET",
                "summary": "Search drug recalls"
        },
        {
                "path": "/v1/webhooks/recalls",
                "method": "POST",
                "summary": "Register a webhook for new recall notifications"
        }
]
    }


@app.get("/v1/recalls/search")
@limiter.limit(RATE_LIMIT)
async def search_drug_recalls(request: Request, drug_name: str = None, ndc: str = None, manufacturer: str = None, classification: str = None, limit: int = 20, x_api_key: str = Header(None)):
    """Search drug recalls"""
    require_auth(x_api_key)
    limit = min(int(request.query_params.get("limit", 25)), 100)
    data = fetcher.fetch_fda_recalls(limit=limit)
    return {"success": True, "count": len(data), "data": data, "source": "live", "cached_at": datetime.utcnow().isoformat()}



@app.post("/v1/webhooks/recalls")
@limiter.limit(RATE_LIMIT)
async def register_a_webhook_for_new_recall_notifications(request: Request, x_api_key: str = Header(None)):
    """Register a webhook for new recall notifications"""
    require_auth(x_api_key)
    limit = min(int(request.query_params.get("limit", 10)), 50)
    data = fetcher.fetch_fda_recalls(limit=limit)
    return {"success": True, "data": data[0] if data else {}, "source": "live"}




# ── Entrypoint ──────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
